<?php  if (!defined('BASEPATH')) exit('No direct script access allowed');
header("Content-Type:text/html; charset=UTF-8");
ini_set('mssql.charset', 'UTF-8');
class sql_query 
{
   


   public function __construct()
   {
   		//echo "Load Complete!"; exit;
   }

/* @ORACLE */

   public function GETDATA_RECEIVEFORCAST()
   {
	   	$sql_str = "
	   	SELECT 
					ROWNUM NO
					,RE.*
					FROM
					(
						SELECT
						 A.PLANT_CD
						,VM.PARENT_SEC_CD
						,A.SOURCE_CD
						,B.SOURCE_NAME
						,A.ITEM_CD
						,MI.ITEM_NAME
						,CASE WHEN substr( A.ITEM_CD, 1,1) = 'P' AND LENGTH(A.ITEM_CD) = 5 THEN 'Packing' ELSE MP.MODEL END MODEL
						,NVL(SUM(CASE WHEN A.TYPE = 5 AND TO_CHAR(A.SDATE,'YYYY/MM/DD') >= TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,0),'MM'),'YYYY/MM/DD') AND  TO_CHAR(A.SDATE,'YYYY/MM/DD') <= TO_CHAR(LAST_DAY(TRUNC(ADD_MONTHS(SYSDATE,0),'MM')),'YYYY/MM/DD') THEN A.QTY END ),0) AS PLAN_CURRENT_MONTH
						,NVL(SUM(CASE WHEN A.TYPE = 5 AND TO_CHAR(A.SDATE,'YYYY/MM/DD') >= TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,0),'MM'),'YYYY/MM/DD') AND  TO_CHAR(A.SDATE,'YYYY/MM/DD') <= TO_CHAR(LAST_DAY(TRUNC(ADD_MONTHS(SYSDATE,0),'MM')),'YYYY/MM/DD') THEN A.PEICE_AMOUNT END ),0)  AS PLAN_CURRENT_AMOUNT
						,NVL(SUM(CASE WHEN A.TYPE = 5 AND TO_CHAR(A.SDATE,'YYYY/MM/DD') >= TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,1),'MM'),'YYYY/MM/DD') AND  TO_CHAR(A.SDATE,'YYYY/MM/DD') <= TO_CHAR(LAST_DAY(TRUNC(ADD_MONTHS(SYSDATE,1),'MM')),'YYYY/MM/DD') THEN A.QTY END ),0) AS PLAN_NEXT_MONTH
						,NVL(SUM(CASE WHEN A.TYPE = 5 AND TO_CHAR(A.SDATE,'YYYY/MM/DD') >= TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,1),'MM'),'YYYY/MM/DD') AND  TO_CHAR(A.SDATE,'YYYY/MM/DD') <= TO_CHAR(LAST_DAY(TRUNC(ADD_MONTHS(SYSDATE,1),'MM')),'YYYY/MM/DD') THEN A.PEICE_AMOUNT END ),0)  AS PLAN_AMOUNT
						FROM
						(
						SELECT
						 5 AS TYPE
						,TD.PLANT_CD AS PLANT_CD
						,TD.SOURCE_CD AS SOURCE_CD
						,TD.ITEM_CD AS ITEM_CD
						,TD.PRD_DUE_DATE AS SDATE
						,PU.UNIT_COST * TD.ODR_QTY AS PEICE_AMOUNT
						,TD.ODR_QTY AS QTY

						FROM
						     ( SELECT * FROM T_OD WHERE OD_TYP = 2 AND OUTSIDE_TYP = 2 AND NOT (ODR_STS_TYP = 9 AND TOTAL_RCV_QTY = 0)) TD
						    ,( SELECT * FROM M_PUCH_UNIT_COST WHERE (EFF_PHASE_OUT_DATE IS NULL OR EFF_PHASE_OUT_DATE >= SYSDATE) ) PU
						WHERE 
						       TD.ITEM_CD = PU.ITEM_CD(+)
						   AND TD.SOURCE_CD = PU.VEND_CD(+)
						   
						)A
						,VM_DEPARTMENT_CLASS VM
						,M_ITEM MI
						,M_PLANT_ITEM MP
						,(SELECT SEC_CD AS SOURCE_CD ,SEC_NM AS SOURCE_NAME FROM VM_DEPARTMENT UNION ALL SELECT VEND_CD AS SOURCE_CD ,VEND_ANAME AS SOURCE_NAME FROM M_VEND_CTRL) B
						WHERE
						    A.SOURCE_CD = VM.COMP_SEC_CD(+)
						AND A.ITEM_CD = MI.ITEM_CD(+)
						AND A.SOURCE_CD = B.SOURCE_CD(+)
						AND A.ITEM_CD = MP.ITEM_CD
						AND A.PLANT_CD = MP.PLANT_CD(+)
						AND A.TYPE IN (3,4,5)
						GROUP BY
						 A.PLANT_CD
						,VM.PARENT_SEC_CD
						,A.SOURCE_CD
						,B.SOURCE_NAME
						,A.ITEM_CD
						,MI.ITEM_NAME
						,MP.MODEL    

						UNION ALL

						SELECT
						 A.PLANT_CD
						,VM.PARENT_SEC_CD
						,A.SOURCE_CD
						,B.SOURCE_NAME
						,A.ITEM_CD
						,MI.ITEM_NAME
						,MP.MODEL
						,NVL(SUM(CASE WHEN A.TYPE = 99 AND TO_CHAR(A.SDATE,'YYYY/MM/DD') >= TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,0),'MM'),'YYYY/MM/DD') AND  TO_CHAR(A.SDATE,'YYYY/MM/DD') <= TO_CHAR(LAST_DAY(TRUNC(ADD_MONTHS(SYSDATE,0),'MM')),'YYYY/MM/DD') THEN A.QTY END ),0) AS PLAN_CURRENT_MONTH
						,0 AS PLAN_CURRENT_AMOUNT
						,NVL(SUM(CASE WHEN A.TYPE = 99 AND TO_CHAR(A.SDATE,'YYYY/MM/DD') >= TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,1),'MM'),'YYYY/MM/DD') AND  TO_CHAR(A.SDATE,'YYYY/MM/DD') <= TO_CHAR(LAST_DAY(TRUNC(ADD_MONTHS(SYSDATE,1),'MM')),'YYYY/MM/DD') THEN A.QTY END ),0) AS PLAN_NEXTMONTH
						,0 AS PLAN_AMOUNT          
						FROM
						(
						SELECT
						 99 AS TYPE
						,TD.PLANT_CD AS PLANT_CD
						,TW.WS_CD AS SOURCE_CD
						,TW.ITEM_CD AS ITEM_CD
						,TD.ODR_PLAN_DATE AS SDATE
						,NULL AS PEICE_AMOUNT
						,TD.ODR_QTY AS QTY
						FROM
						 (SELECT
								 WS_CD
								,ITEM_CD
							FROM
								 T_WORK_IN_PROC_BY_PROC TW
								,VM_DEPARTMENT_CLASS VC
							WHERE
								 TW.WS_CD = VC.COMP_SEC_CD(+)
							--AND VC.PARENT_SEC_CD = 'K1PD04'
							GROUP BY
								 WS_CD
								,ITEM_CD
								ORDER BY 1 ) TW 
						,T_OD TD
						WHERE 
						    TW.ITEM_CD = TD.ITEM_CD(+)
						AND NOT(TD.ODR_STS_TYP = 9 AND TD.ODR_QTY = 0)

						)A
						,VM_DEPARTMENT_CLASS VM
						,M_ITEM MI
						,M_PLANT_ITEM MP
						,(SELECT SEC_CD AS SOURCE_CD ,SEC_NM AS SOURCE_NAME FROM VM_DEPARTMENT UNION ALL SELECT VEND_CD AS SOURCE_CD ,VEND_ANAME AS SOURCE_NAME FROM M_VEND_CTRL) B
						WHERE
						    A.SOURCE_CD = VM.COMP_SEC_CD(+)
						AND A.ITEM_CD = MI.ITEM_CD(+)

						AND A.SOURCE_CD = B.SOURCE_CD(+)
						AND A.ITEM_CD = MP.ITEM_CD
						AND A.PLANT_CD = MP.PLANT_CD
						AND VM.PARENT_SEC_CD = 'K1PD04'
						GROUP BY
						 A.PLANT_CD
						,VM.PARENT_SEC_CD
						,A.SOURCE_CD
						,B.SOURCE_NAME
						,A.ITEM_CD
						,MI.ITEM_NAME
						,MP.MODEL
						ORDER BY 2,3,4 DESC
					)RE
	   	";

	   	return $sql_str;
   }



/* @MySQL@ */





}
// END Template Class

/* End of file Template.php */
/* Location: ./system/application/libraries/Template.php */